[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka.variants]
  inherits = "ss12"

    [buildPlans.iosevka.variants.design]
    capital-i = "short-serifed"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-j = "serifed"
    capital-s = "serifless"
    a = "double-storey-serifless"
    g = "double-storey"
    cyrl-che = "standard"
    cyrl-capital-u = "straight-serifless"
    zero = "slashed"
    one = "no-base"
    two = "straight-neck"
    four = "closed-non-crossing"
    five = "upright-flat"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "straight-bar"
    tilde = "low"
    asterisk = "hex-low"
    paren = "normal"
    brace = "straight"
    dollar = "through"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    punctuation-dot = "round"
    i = "tailed-serifed"
    j = "serifed"
    l = "tailed-serifed"
